version: "3.7"
services:
  postgres:
    container_name: drizzle-next-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - drizzle-next-postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  drizzle-next-postgres-vol:
